Docker-compose-wait starting with configuration:
------------------------------------------------
 - Hosts to be waiting for: [api:4000, frontend:3000, nginx-proxy:80]
 - Timeout before failure: 30 seconds
 - Sleeping time before checking for hosts availability: 0 seconds
 - Sleeping time once all hosts are available: 0 seconds
------------------------------------------------
Checking availability of api:4000
Host api:4000 not yet available
Host api:4000 not yet available
Host api:4000 not yet available
Host api:4000 not yet available
Host api:4000 not yet available
Host api:4000 not yet available
Host api:4000 not yet available
Host api:4000 not yet available
Host api:4000 not yet available
Host api:4000 not yet available
Host api:4000 not yet available
Host api:4000 not yet available
Host api:4000 not yet available
Host api:4000 is now available
Checking availability of  frontend:3000
Host  frontend:3000 is now available
Checking availability of  nginx-proxy:80
Host  nginx-proxy:80 is now available
2019/09/05 02:21:31 Generated '/app/letsencrypt_service_data' from 5 containers
2019/09/05 02:21:31 Running '/app/signal_le_service'
2019/09/05 02:21:31 Watching docker events
2019/09/05 02:21:31 Contents of /app/letsencrypt_service_data did not change. Skipping notification '/app/signal_le_service'
/etc/nginx/certs/api.sungryeol.xyz /app
Reloading nginx proxy (1ff0f1d6a04f38b84deefc49dfda967de11253cdf7059d22dca5eeaf92920978)...
2019/09/05 02:21:32 Contents of /etc/nginx/conf.d/default.conf did not change. Skipping notification ''
2019/09/05 02:21:32 [notice] 65#65: signal process started
Creating/renewal api.sungryeol.xyz certificates... (api.sungryeol.xyz)
2019-09-05 02:21:35,151:INFO:simp_le:1479: Generating new certificate private key
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/simp_le.py", line 1419, in get_certr
    max_attempts=(10 * len(authorizations)))
  File "/usr/lib/python3.6/site-packages/acme/client.py", line 482, in poll_and_request_issuance
    raise errors.PollError(exhausted, updated)
acme.errors.PollError
docker-full-stack_nginx-letsencrypt.1.jdjwp51hqq2p@sungryeol    |
During handling of the above exception, another exception occurred:
docker-full-stack_nginx-letsencrypt.1.jdjwp51hqq2p@sungryeol    |
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/simp_le.py", line 1583, in main
    return main_with_exceptions(cli_args)
  File "/usr/lib/python3.6/site-packages/simp_le.py", line 1567, in main_with_exceptions
    persist_new_data(args, existing_data)
  File "/usr/lib/python3.6/site-packages/simp_le.py", line 1483, in persist_new_data
    certr = get_certr(client, csr, authorizations)
  File "/usr/lib/python3.6/site-packages/simp_le.py", line 1425, in get_certr
    ', '.join(authzr.uri for _, authzr in error.exhausted)
  File "/usr/lib/python3.6/site-packages/simp_le.py", line 1425, in <genexpr>
    ', '.join(authzr.uri for _, authzr in error.exhausted)
ValueError: too many values to unpack (expected 2)
docker-full-stack_nginx-letsencrypt.1.jdjwp51hqq2p@sungryeol    |
Unhandled error has happened, traceback is above
docker-full-stack_nginx-letsencrypt.1.jdjwp51hqq2p@sungryeol    |
Debugging tips: -v improves output verbosity. Help is available under --help.
/app